export { default as Hero } from './Hero/Hero'
export { default as About } from './About/About'
export { default as Experience } from './Experience/Experience'
export { default as Education } from './Education/Education'
export { default as Projects } from './Projects/Projects'
export { default as Skills } from './Skills/Skills'
export { default as Services } from './Services/Services'
export { default as Contact } from './Contact/Contact'
